### ISSUE TITLE
Is this project still maintained/developed? 

### ISSUE THREAD

**Issue by dryajov** [getherbert/herbert#112]

**Comment by dcalvert** [comment]
I don't think theres much happening anymore on this project :(

**Comment by onnimonni** [comment]
Hey guys! I hear your concerns... @jasonagnew has been super busy with other projects and as the creator of this framework has the best viewpoints where Herbert should be be headed in the future.

I volunteered to help with development of Herbert but sadly I haven't found much time for this too.

We would really want to continue development of herbert and you're welcome to join us if you want to.

I saw that you guys have been putting a lot of effort into issues/PRs. Would you be interested in helping us out @dryajov @dcalvert @imboden @jeremyzahner?

**Comment by dryajov** [comment]
I would. At least for the current project I'm working on I've decided to use this instead of themosis, because it's less invasive. I'm willing to help. 

So far the most pressing missing feature is rendering custom content inside posts. I've opened another issue #111 and willing to implement that first. Please share thoughts/ideas on whats the best approach there.

**Comment by jeremyzahner** [comment]
@onnimonni I'd be willing to take over some maintenance work, such as managing pull requests and issues, doing code reviews and stuff like that. Since we are mostly working on angular and react projects at the moment, I think I might not be able to do a lot of development itself (at least right now).

Let me know if that's something that would help you guys. Since there are a lot of open issues atm one might think it does.

**Comment by dcalvert** [comment]
@onnimonni I have a couple of projects to ship, after that I should have some time to help out.
