### ISSUE TITLE
Extending another WP Plugin to Herbert Framework

### ISSUE THREAD

**Issue by muubpon** [getherbert/herbert#150]
Good day everyone!

I'm new to WP, this is my first time to create a plugin (actually, I already developed a simple WP plugin using herbert).

I installed plenty of WP plugins online and studied it. Unfortunately, I can't figure out how can I use/embed an existing plugin to mine (herbert framework). I read a lot of articles about extending plugin but I don't have any idea on how to integrate to herbert. Any suggestions?

**Comment by sajadghawami** [comment]
hey,

your question seems to be too general... be more specific please... what do u want to implement exactly?

**Comment by muubpon** [comment]
I want to use existing (develop by other developer) plugin to my develop herbert-based plugin. How could I do that?

**Comment by jan-koch** [comment]
I guess you'd have to migrate the existing plugin into the MVC concept used by Herbert.

**Comment by jeremyzahner** [comment]
@faidz-ubpon Just like @jan-koch said, there is no easy way just to plug and play an existing (nonMVC oriented) plugin into the one built on top of Herbert. I don't see the point of it either since the plugin is already existing? So to answer your question: Study the existing plugins functionality, understand how it does what it does, refactor that into your Herbert-based Plugin.

I'm closing the issue. Feel free to reopen it if you feel that your problem hasn't been addressed properly.
