### ISSUE TITLE
Use with Timber

### ISSUE THREAD

**Issue by aristath** [getherbert/herbert#3]
First of all awesome work, so far by reading the docs I can say I'm really impressed!

However I have 1 question...
In my themes and plugins I use twig by requiring the installation of Timber: https://github.com/jarednova/timber

I've grown quite fond of it and it's really amazing... I'd love to be able to use both Herbert and Timber.
Is there an easy way to replace Herbert's Twig classes with Timber on my plugins?

I just thought of asking before I start working on my implementations...

**Comment by jasonagnew** [comment]
Thanks for giving Herbert a go.

From looking at Timber it uses composer so that will it easier to implement. Though I wonder if you will run into issues with it pulling stuff from the current WordPress theme. If I was going it, I’d add:

`"jarednova/timber": "dev-master"`

To my composer file, run `composer update`. Then include and set Timber up in the BaseController so all controllers can access it.

**Comment by jeremyzahner** [comment]
@aristath Did you manage to get this setup up and running? Would you be open to provide the community with your setup's details? Personally, I think timber and Herbert could be a match made in heaven.

**Comment by aristath** [comment]
That was a long time ago! I never completed the integration... I stopped using twig and I'm now using underscore.js templates instead.

**Comment by jeremyzahner** [comment]
I guess we will close this issue for now since an integration with timber is not a real requirement. Since I will be using Herbert with timber shortly, I will be looking at this anyway.
