### ISSUE TITLE
What's the real difference?

### ISSUE THREAD

**Issue by mbnoimi** [getherbert/herbert#33]
Today I read about [Themosis Framework](https://github.com/themosis/themosis) I wonder what's the real difference between Herbert Framework and Themosis Framework?

AFAIK Themosis has same features of Herbert with two small differences:
1. Themosis supports custom types
2. Themosis creates an app linked to WordPress while Herbert creates a real WP plugin.

**Comment by jasonagnew** [comment]
Hi @mbnoimi 

I’m not too familiar with Themosis but I would imagine it was born out of similar frustrations to what made me start Herbert. You can tell both are heavily influenced by Laravel. However, Themosis is designed as a platform to help users build out better site/applications, there tag line is:

Build custom websites and applications with WordPress.

Herbert is designed to make writing plugins for WordPress easier. Its good practise to extend WordPress through a plugin, say for example I needed use Mailgun to send emails on new client site - I would build that into a plugin as it’s not theme related. And if your agency or development shop you might build up an internal list of plugins that make writing WordPress sites quicker and easier as they act like modules. 

And with Herbert I don’t intend to hide the way WordPress works, just make some of the annoying stuff easier. 

If your checking out different options then I suggest you also look into:

The WordPress Plugin Bolierplate: http://wppb.io/
Bedrock: https://roots.io/
Underscores: http://underscores.me/
Layers: http://www.layerswp.com/

**Comment by mbnoimi** [comment]
@jasonagnew Thanks for the response.

> with Herbert I don’t intend to hide the way WordPress works, just make some of the annoying stuff easier. 

Does Herbert supports back-end for the deployed plugin? May you please publish what's the difference between creating a WordPress plugin from scratch and creating a WordPress plugin using Herbert. I'm really confused I couldn't understand how Herbert isn't a bolierplate.

> If your checking out different options then I suggest you also look into:
> The WordPress Plugin Bolierplate: http://wppb.io/
> Bedrock: https://roots.io/
> Underscores: http://underscores.me/
> Layers: http://www.layerswp.com/

I found Bedrock very similar to Themosis does it? Both of them works for custom WordPress website not WordPress plugin.

**Comment by richjenks** [comment]
I may be completely off-the-mark here, but from what I can tell, Themosis is more concerned with using WP as an application framework (not necessarily using the WP front-end) whereas Herbert seems more concerned with making developing WP plugins easier, more consistent and a bit more grown-up.

IMO there's a massive gap in the market for something like Herbert that provides structure to plugin development and the sooner it [plays well with itself](https://github.com/getherbert/herbert/issues/23) the better :)

**Comment by jasonagnew** [comment]
Thanks @richjenks you've explained it well. And as of 2 days ago Herbert now plays well with itself (v0.9.5) :) I've got a few small changes to make this week and then a second pass over the docs.

**Comment by richjenks** [comment]
Wonderful! That would have been my only hesitation with using Herbert in the wild.

**Comment by mbnoimi** [comment]
I know this is out the scope but may you please see my question in Stackoverflow:

WordPress framework which type? 
http://stackoverflow.com/questions/30603526/wordpress-framework

I really appreciate your contributions :)

**Comment by mbnoimi** [comment]
Hell no, It seems Stackoverflow keen to reject many questions,  any way I posted my question in WordPress forums hopeful to get a useful answer:
https://wordpress.org/support/topic/which-type-of-frameworks?replies=1#post-7023245

**Comment by jasonagnew** [comment]
@mbnoimi  I don’t feel this suits a Github issue but I can see from StackOverflow your not having much luck getting the answers you need so I’ll try my best to offer some advice.

I think you need to break this question up a little - there is no project that will do everything for you. 

So to start with: decide if you need a framework or CMS.

My rule for this and I think it’s true in most cases. If the site/app your building requires visitors to sign up for an account and carry out actions then you should be using a framework. So both your HR & CRM fit that.

You’ve made it clear your planning to use PHP. So theres a lot to choice from - [check out this survey](http://www.sitepoint.com/best-php-framework-2015-sitepoint-survey-results/)

Personally I think Laravel would be the best option for you - mainly because [Laracasts](https://laracasts.com/) makes learning it so simple.

Now you need to select a front-end/UI kit to go with it. If you want to do it right then set up a good automation workflow with Gulp & SASS. I’m just going to list some interesting projects for you to check out as I don’t feel I’m the right guy to advice you on it.

Bootstrap: http://getbootstrap.com/
Polymer: https://www.polymer-project.org/1.0/
Bourbon, Neat etc.: http://bourbon.io/

A great place to learn all sorts is [Code School](https://www.codeschool.com/). And if you want to ask people more about the PHP side of stuff, look into [Reddit](http://www.reddit.com/r/PHP/) or join IRCs / Slack channels for projects.

**Comment by mbnoimi** [comment]
@jasonagnew Thanks a lot for good advice.
UPDATE: I think this thread has to be closed.
